# Generated by Django 4.1 on 2022-09-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_file_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaBit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=100)),
                ('hour', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
                ('altitude', models.FloatField(max_length=100)),
                ('statype', models.CharField(max_length=100)),
                ('senstype', models.CharField(max_length=100)),
                ('statnum', models.CharField(max_length=100)),
                ('sensnum', models.CharField(max_length=100)),
                ('flname', models.CharField(max_length=100)),
                ('freq', models.FloatField(max_length=100)),
                ('duration', models.FloatField(max_length=100)),
                ('windopts', models.CharField(max_length=100)),
                ('rainopts', models.CharField(max_length=100)),
                ('temp', models.FloatField(max_length=100)),
                ('remarkstemp', models.CharField(max_length=100)),
                ('groundtyp', models.CharField(max_length=100)),
                ('remarksgro', models.CharField(max_length=100)),
                ('observations', models.CharField(max_length=100)),
            ],
        ),
    ]
