# Generated by Django 4.1 on 2022-09-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_pruebabit_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebabit',
            name='documento',
            field=models.FileField(blank=True, default=1, upload_to='bitacora/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='observations',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
