# Generated by Django 4.1 on 2022-09-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_pruebabit_is_completed_pruebabit_revisado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebabit',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor del archivo'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='duration',
            field=models.FloatField(max_length=100, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='freq',
            field=models.FloatField(max_length=100, verbose_name='Frecuencia (Hz)'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Archivo'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='rainopts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condiciones de Lluvia'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='remarksgro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones de Tierra'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='remarkstemp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones de temperatura'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='windopts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condiciones de Viento'),
        ),
    ]
