# Generated by Django 4.1 on 2022-09-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pruebabit_freq2_alter_pruebabit_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruebabit',
            name='flname',
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='altitude',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Altitud'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='duration',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='freq',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Frecuencia (Hz)'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='freq2',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Frecuencia (Hz)'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='latitude',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='longitude',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='temp',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Temperatura'),
        ),
    ]
