# Generated by Django 4.1 on 2022-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_pruebabit_observations_alter_pruebabit_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Graficos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xarch", models.FileField(blank=True, upload_to="bitacora/")),
                ("yarch", models.FileField(blank=True, upload_to="bitacora/")),
                ("zarch", models.FileField(blank=True, upload_to="bitacora/")),
            ],
        ),
        migrations.CreateModel(
            name="Infinitos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medtype", models.CharField(blank=True, max_length=100, null=True)),
                ("medicion", models.FloatField(blank=True, max_length=100, null=True)),
                ("unidad", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="pruebabit",
            name="Estruc",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Estructura"
            ),
        ),
        migrations.AddField(
            model_name="pruebabit",
            name="Traf",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Trafico"
            ),
        ),
        migrations.AddField(
            model_name="pruebabit",
            name="clima",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Clima"
            ),
        ),
        migrations.AlterField(
            model_name="pruebabit",
            name="observations",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Observaciones"
            ),
        ),
        migrations.AlterField(
            model_name="pruebabit",
            name="place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
