# Generated by Django 4.1 on 2022-10-09 14:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="prueba",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(verbose_name="Contenido"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pics", verbose_name="Imagen"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.CharField(max_length=130, verbose_name="Titulo-URL"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titulo"),
        ),
    ]
