# Generated by Django 4.1 on 2022-10-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_rename_prueba_comment_prueba2_blogpost_prueba"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="prueba2", new_name="prueba",
        ),
    ]
