# Generated by Django 4.1 on 2022-10-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
