# Generated by Django 4.1 on 2022-10-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_registros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='bio',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='registros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registros',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
