# Generated by Django 4.1 on 2022-10-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_bio_registros_first_name_registros_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registros',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registros',
            name='revisado',
            field=models.BooleanField(default=False, verbose_name='Revisado'),
        ),
    ]
