# Generated by Django 4.1 on 2022-10-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_registros_observaciones_registros_revisado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruebabit',
            name='medicion',
        ),
        migrations.AddField(
            model_name='pruebabit',
            name='medición',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=8, null=True),
        ),
    ]
