# Generated by Django 4.1 on 2022-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_remove_pruebabit_prueba"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pruebabit",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Publicado"),
        ),
        migrations.DeleteModel(name="Comment",),
    ]
