# Generated by Django 4.1 on 2022-10-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0039_alter_pruebabit_is_completed_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(
                max_length=130, unique=True, verbose_name="Titulo-URL"
            ),
        ),
    ]
