global:
  checkNewVersion: true
  sendAnonymousUsage: true

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ':443'

  traefik:
    address: ':8080'

log:
  level: DEBUG
  filePath: /etc/traefik/logs/traefik.log

accessLog:
  filePath: /etc/traefik/logs/access.log

api:
  insecure: true
  dashboard: true
  debug: true

ping: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

  file:
    filename: /etc/traefik/dynamic-conf.yml
    watch: true


