# Generated by Django 4.1 on 2022-08-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Documentos',
        ),
    ]
