# Generated by Django 4.1 on 2022-09-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pruebabit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebabit',
            name='altitude',
            field=models.FloatField(max_length=100, verbose_name='Altitud'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='fecha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='flname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='groundtyp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='hour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='latitude',
            field=models.FloatField(max_length=100, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='longitude',
            field=models.FloatField(max_length=100, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='observations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='rainopts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='remarksgro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='remarkstemp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='sensnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='senstype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Sensor'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='statnum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='statype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Estación'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='windopts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
