# Generated by Django 4.1 on 2022-09-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_pruebabit_altitude_alter_pruebabit_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebabit',
            name='autor',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebabit',
            name='documento',
            field=models.FileField(default=0, upload_to='bitacoras/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruebabit',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
