# Generated by Django 4.1 on 2022-09-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_pruebabit_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebabit',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Revisado'),
        ),
        migrations.AddField(
            model_name='pruebabit',
            name='revisado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='flname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Archivo'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='groundtyp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Suelo'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='observations',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='sensnum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='# de Sensor'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='statnum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='# de Estación'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='temp',
            field=models.FloatField(max_length=100, verbose_name='Temperatura'),
        ),
    ]
