# Generated by Django 4.1 on 2022-09-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_pruebabit_autor_alter_pruebabit_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebabit',
            name='freq2',
            field=models.FloatField(default=0, max_length=100, verbose_name='Frecuencia (Hz)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
