# Generated by Django 4.1 on 2022-09-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_pruebabit_flname_alter_pruebabit_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebabit',
            name='observations',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='pruebabit',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar'),
        ),
    ]
