# Generated by Django 4.1 on 2022-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_graficos_infinitos_pruebabit_estruc_pruebabit_traf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pruebabit",
            name="Prueba",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Clima"
            ),
        ),
    ]
