# Generated by Django 4.1 on 2022-09-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_graficos_nomx_graficos_nomy_graficos_nomz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebabit',
            name='altitude',
            field=models.FloatField(blank=True, default=0.0, max_length=100, null=True, verbose_name='Altitud'),
        ),
    ]
