# Generated by Django 4.1 on 2022-10-09 14:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_comment_prueba_alter_blogpost_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="prueba", new_name="prueba2",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="prueba",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
