# Generated by Django 4.1 on 2022-10-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_pruebabit_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruebabit',
            old_name='dateTime',
            new_name='dateNow',
        ),
    ]
