# Generated by Django 4.1 on 2022-10-13 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0030_pruebabit_author_alter_blogpost_prueba"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pruebabit",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
