# Generated by Django 4.1 on 2022-10-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_pruebabit_medicion_pruebabit_medición'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruebabit',
            name='Prueba',
        ),
    ]
